### ISSUE TITLE
Navigation don't scroll to position with cyrillic characters ids

### ISSUE THREAD

**Issue by ANONIMNIQ** [tscanlin/tocbot#293] opened 2022-11-28 21:45 UTC
How to make navigation to work with cyrillic language? If I paste the link in browser it load page to the right position, but toc menu only changes when I scroll to id positions but don't work If I click on the menu.

**Comment by tscanlin** [comment] 2022-11-29 03:55
Hey, sorry to hear you are running into an issue. Do you have a link that I could see that reproduces this issue?

**Comment by ANONIMNIQ** [comment] 2022-11-29 10:49
[https://e-kni.ga/miezhdu-ada-i-raia-chast1/](url)

**Comment by tscanlin** [comment] 2022-12-02 05:05
I think this is because the id's are encoded:
`%D1%87%D0%B0%D1%81%D1%82-1%D0%B4%D0%B8%D0%B0%D0%BB%D0%BE%D0%B3-%D1%81-%D0%B4%D1%8F%D0%B2%D0%BE%D0%BB%D0%B0`
When I change the id to the unicode characters it seems to work.

**Comment by ANONIMNIQ** [comment] 2022-12-02 06:42
My site is in Bulgarian language and there is a lot of cyrillic characters. Any way to fix this?

**Comment by tscanlin** [comment] 2022-12-02 07:27
Actually this should be fixed in the latest version. I think you are on `4.11.1` and you should switch to the latest `4.19.0` and that should hopefully fix the issue. see also: https://github.com/tscanlin/tocbot/issues/281#issuecomment-1178618689

**Comment by ANONIMNIQ** [comment] 2022-12-02 07:31
Thank you! 4.19.0 solved the issue!

**Closed** 2022-12-02 07:33 UTC
